{{- if not .Values.discord.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-discord
type: Opaque
stringData:
  DISCORD_TOKEN: {{ required "discord.token is required" .Values.discord.token | quote }}
{{- end }}
